kind: pipeline
name: default

steps:
- name: build
  image: node
  commands:
  - npm install
  - npm run build
- name: deploy
  image: drillster/drone-rsync
  settings:
    hosts:
      from_secret: my_blog_host
    port:
      from_secret: my_blog_port
    key:
      from_secret: my_blog_key
    target:
      from_secret: my_blog_key
    source: /drone/src/build/*
    recursive: true
    delete: true
